---
language: python
python: "3.8.5"
before_install:
 - sudo apt-get update 
 - sudo apt-get -y install python-pycurl
install:
  - sudo apt -y install ansible
script:
  - echo travis.dev > inventory
  - ansible-playbook -i inventory --syntax-check --list-tasks test.yml
  - ansible-playbook -i inventory --extra-vars "ssl_certs_common_name=travis.dev" --connection=local --sudo -vvvv test.yml
addons:
  hosts:
    - travis.dev
